/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bavard;

import bavard.user.UserIdentifier;

import java.util.Scanner;

public class App {

    public String getGreeting() {
        UserIdentifier ui = new UserIdentifier();
        return ui.identifyUser();
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
